import { existsSync, mkdirSync } from "node:fs";
import { createServer } from "node:net";
import { homedir } from "node:os";
import { posix, win32 } from "node:path";
import { chromeDiagnostic } from "../lib.ts";
import { CdpConnection } from "./cdp.ts";

type Platform = "darwin" | "win32" | "linux" | string;
type Environment = Record<string, string | undefined>;
type ExecutableLookup = (name: string) => string | null;

export type ChromeBrowserOptions = {
  launch?: boolean;
  timeoutMs?: number;
  executable?: string;
  profileDir?: string;
  launchArguments?: string[];
};

export function chromeLaunchCommand(
  executable: string,
  profileDir: string,
  debugPort: number,
  launchArguments: string[] = [],
): string[] {
  return [
    executable,
    `--user-data-dir=${profileDir}`,
    "--remote-debugging-address=127.0.0.1",
    `--remote-debugging-port=${debugPort}`,
    "--no-first-run",
    "--no-default-browser-check",
    "--install-autogenerated-theme=255,165,0",
    ...launchArguments,
  ];
}

type DevToolsEndpoint = {
  port: number;
  path: string;
  url: string;
};

export function chromeProfileDirectory(
  platform: Platform = process.platform,
  environment: Environment = process.env,
  userHome = homedir(),
): string {
  const join = platform === "win32" ? win32.join : posix.join;
  if (environment.OX_CHROME_PROFILE) return environment.OX_CHROME_PROFILE;
  if (platform === "darwin") return join(userHome, "Library", "Application Support", "Ox", "Chrome");
  if (platform === "win32") {
    return join(environment.LOCALAPPDATA ?? join(userHome, "AppData", "Local"), "Ox", "Chrome");
  }
  return join(environment.XDG_DATA_HOME ?? join(userHome, ".local", "share"), "ox", "chrome");
}

export function findChromeExecutable(
  platform: Platform = process.platform,
  environment: Environment = process.env,
  executableLookup: ExecutableLookup = (name) => Bun.which(name),
  pathExists: (path: string) => boolean = existsSync,
  userHome = homedir(),
): string | undefined {
  const join = platform === "win32" ? win32.join : posix.join;
  const override = environment.OX_CHROME_PATH;
  if (override) return pathExists(override) ? override : undefined;
  const candidates: string[] = [];
  if (platform === "darwin") {
    candidates.push(
      "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
      join(userHome, "Applications", "Google Chrome.app", "Contents", "MacOS", "Google Chrome"),
    );
  } else if (platform === "win32") {
    for (const root of [environment.LOCALAPPDATA, environment.PROGRAMFILES, environment["PROGRAMFILES(X86)"]]) {
      if (root) candidates.push(join(root, "Google", "Chrome", "Application", "chrome.exe"));
    }
  } else {
    for (const name of ["google-chrome-stable", "google-chrome"]) {
      const found = executableLookup(name);
      if (found) candidates.push(found);
    }
  }
  return candidates.find(pathExists);
}

export class ChromeBrowser {
  private constructor(
    readonly profileDir: string,
    readonly endpoint: DevToolsEndpoint,
    readonly cdp: CdpConnection,
  ) {}

  static async connect(options: ChromeBrowserOptions = {}): Promise<ChromeBrowser | undefined> {
    const profileDir = options.profileDir ?? chromeProfileDirectory();
    const timeoutMs = options.timeoutMs ?? 10_000;
    const existing = await this.connectExisting(profileDir);
    if (existing || options.launch === false) return existing;
    const executable = options.executable ?? findChromeExecutable();
    if (!executable) throw new Error("Google Chrome was not found; install Chrome or set OX_CHROME_PATH");
    mkdirSync(profileDir, { recursive: true });
    const debugPort = await availableLoopbackPort();
    await Bun.write(chromePortFile(profileDir), `${debugPort}\n`);
    chromeDiagnostic("starting headed Chrome");
    const process = Bun.spawn({
      cmd: chromeLaunchCommand(executable, profileDir, debugPort, options.launchArguments),
      stdin: "ignore",
      stdout: "ignore",
      stderr: "ignore",
      detached: true,
    });
    process.unref();
    const deadline = performance.now() + timeoutMs;
    while (performance.now() < deadline) {
      const browser = await this.connectExisting(profileDir);
      if (browser) return browser;
      await Bun.sleep(100);
    }
    throw new Error(`Chrome did not expose CDP within ${timeoutMs}ms`);
  }

  close(): void {
    this.cdp.close();
  }

  private static async connectExisting(profileDir: string): Promise<ChromeBrowser | undefined> {
    const port = await readPort(Bun.file(chromePortFile(profileDir)));
    if (!port) return undefined;
    const endpoint = await endpointForPort(port);
    if (!endpoint) return undefined;
    try {
      const cdp = await CdpConnection.connect(endpoint.url, 500);
      await cdp.send("Browser.getVersion", {}, undefined, 1_000);
      return new ChromeBrowser(profileDir, endpoint, cdp);
    } catch {
      return undefined;
    }
  }
}

async function availableLoopbackPort(): Promise<number> {
  const server = createServer();
  await new Promise<void>((resolve, reject) => {
    server.once("error", reject);
    server.listen(0, "127.0.0.1", resolve);
  });
  const address = server.address();
  if (!address || typeof address === "string") throw new Error("Could not allocate a Chrome debugging port");
  await new Promise<void>((resolve, reject) => server.close((error) => error ? reject(error) : resolve()));
  return address.port;
}

function chromePortFile(profileDir: string): string {
  const separator = process.platform === "win32" ? win32 : posix;
  return separator.join(profileDir, "DevToolsPort");
}

async function readPort(file: ReturnType<typeof Bun.file>): Promise<number | undefined> {
  if (!await file.exists()) return undefined;
  const port = Number((await file.text()).trim());
  return Number.isInteger(port) && port > 0 && port < 65_536 ? port : undefined;
}

async function endpointForPort(port: number): Promise<DevToolsEndpoint | undefined> {
  try {
    const response = await fetch(`http://127.0.0.1:${port}/json/version`, { signal: AbortSignal.timeout(500) });
    if (!response.ok) return undefined;
    const body = await response.json() as { webSocketDebuggerUrl?: string };
    if (!body.webSocketDebuggerUrl) return undefined;
    const websocket = new URL(body.webSocketDebuggerUrl);
    if (websocket.protocol !== "ws:" || Number(websocket.port) !== port) return undefined;
    const path = `${websocket.pathname}${websocket.search}`;
    return { port, path, url: `ws://127.0.0.1:${port}${path}` };
  } catch {
    return undefined;
  }
}
