const pause=ms=>new Promise(r=>setTimeout(r,ms));
async function wait(fn,ms=12000){const end=Date.now()+ms;do{const v=fn();if(v)return v;await pause(120);}while(Date.now()<end);throw Error('Qwen interface not ready');}
async function api(){const s=await wait(()=>[...document.scripts].find(x=>x.src.includes('/qwen-chat-fe/')&&x.src.endsWith('/js/main.js')));const m=await import(s.src);if(typeof m.dN!=='function'||!String(m.dN).includes('/auths/')||typeof m.p!=='function'||!String(m.p).includes('Accept-Language'))throw Error('Qwen website module changed');return m;}
async function identity(){const m=await api();const j=await m.dN(false);if(j?.success===true&&typeof j.data?.id==='string'&&j.data.id&&j.data.role==='user')return j.data;if(j?.success===false&&j.data?.code==='Unauthorized')return null;throw Error('Unexpected Qwen identity response');}
async function request(path,params){const m=await api();const j=await m.p(path,{method:'GET',params,toast:false});if(j?.success!==true)throw Error('Qwen read failed: '+String(j?.data?.code||'unexpected response'));return j.data;}
async function list(page){const a=await request('/chats/',{page,exclude_project:true});if(!Array.isArray(a))throw Error('Unexpected Qwen history');return a;}
window.ox.install(({action})=>{
action('getSignInUrl',{async invoke(){return {url:'https://chat.qwen.ai/'};}});
action('getSignInState',{async invoke(){return {signedIn:!!(await identity())};}});
action('getCurrentUser',{async invoke(){const u=await identity();if(!u)throw Error('Sign in to Qwen');return {id:u.id,name:String(u.name||''),email:String(u.email||'')};}});
action('listModels',{async invoke(){const d=await request('/models/');if(!Array.isArray(d?.data))throw Error('Unexpected model catalog');return {items:d.data.map(x=>({id:String(x.id),name:String(x.name)})),nextCursor:null};}});
action('listConversations',{async invoke(a){const page=Number(a.cursor||1);const items=await list(page);return {items:items.map(x=>({id:String(x.id),title:String(x.title||'')})),nextCursor:items.length?String(page+1):null};}});
action('searchConversations',{async invoke({query,cursor='1'}){if(!query.trim())throw Error('Search query must not be blank');const page=Number(cursor);if(!Number.isSafeInteger(page)||page<1)throw Error('Invalid search cursor');const rows=await request('/chats/search',{text:query,page});if(!Array.isArray(rows)||rows.some(x=>typeof x.id!=='string'||typeof x.title!=='string'))throw Error('Unexpected Qwen search response');return {items:rows.map(x=>({id:x.id,title:x.title,url:'https://chat.qwen.ai/c/'+encodeURIComponent(x.id)})),nextCursor:rows.length?String(page+1):null};}});
action('getConversation',{async invoke(a){return detail(a.conversationId);}});
action('openConversation',{async invoke(a){return openTarget(a.conversationId);}});
action('chat',{async invoke(a){return send(a.message,null);}});
action('continueChat',{async invoke(a){return send(a.message,a.conversationId);}});
action('selectModel',{async invoke(a){const b=await wait(()=>document.querySelector('[aria-label^="Models "]'));if(b.getAttribute('aria-label')==='Models '+a.name)return {selected:a.name};b.click();const option=await wait(()=>[...document.querySelectorAll('[role="option"]')].find(x=>x.querySelector('.mms-list__name-text')?.textContent.trim()===a.name));option.click();await wait(()=>document.querySelector('[aria-label^="Models "]')?.getAttribute('aria-label')==='Models '+a.name);return {selected:a.name};}});
});
async function detail(id){const d=await request('/chats/'+id);if(d?.id!==id||!Array.isArray(d.chat?.messages))throw Error('Qwen conversation identity mismatch');return {id:d.id,title:String(d.title||''),url:'https://chat.qwen.ai/c/'+d.id,messages:d.chat.messages.slice(-100).map(x=>({id:String(x.id),role:String(x.role),text:typeof x.content==='string'&&x.content?x.content:(x.content_list||[]).filter(y=>y.phase==='answer').map(y=>y.content||'').join('\n'),done:x.role==='user'||x.done===true})),hasEarlierMessages:!!d.chat.history?.pagination||d.chat.messages.length>100};}
async function editor(){return wait(()=>document.querySelector('textarea.message-input-textarea'));}
async function openTarget(id){const e=await editor();if(e.value.trim())throw Error('Existing Qwen draft preserved');const d=await detail(id);if(location.pathname!=='/c/'+id){const target=await wait(()=>{const matches=[...document.querySelectorAll('.chat-item-title-text')].filter(x=>x.textContent.trim()===d.title);if(matches.length>1)throw Error('Ambiguous sidebar title');return matches.length===1?matches[0]:null;});target.click();await wait(()=>location.pathname==='/c/'+id);await editor();}return detail(id);}
async function send(message,id){let before;if(id){before=await openTarget(id);}else{const e=await editor();if(e.value.trim())throw Error('Existing Qwen draft preserved');if(location.pathname!=='/'){const b=await wait(()=>document.querySelector('[role="button"][aria-label="New Chat"]'));b.click();await wait(()=>location.pathname==='/');}before=null;}const initial=await list(1);const e=await editor();if(e.value.trim())throw Error('Existing Qwen draft preserved');Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(e,message);e.dispatchEvent(new Event('input',{bubbles:true}));const b=await wait(()=>document.querySelector('button.send-button[aria-label="Send"]'));if(b.disabled||e.value!==message)throw Error('Qwen composer not ready');b.click();let latest=null,confirmed=false;const end=Date.now()+15000;do{await pause(700);if(!id){const now=await list(1);const fresh=now.find(x=>!initial.some(y=>y.id===x.id));if(fresh)id=String(fresh.id);}if(id){latest=await detail(id);const fresh=latest.messages.filter(x=>!before?.messages.some(y=>y.id===x.id));const user=fresh.find(x=>x.role==='user'&&x.text===message);confirmed=!!user;const reply=user&&fresh.slice(fresh.indexOf(user)+1).find(x=>x.role==='assistant'&&x.done&&x.text);if(reply)return {submissionConfirmed:true,status:'completed',conversation:latest};}}while(Date.now()<end);return {submissionConfirmed:confirmed,status:confirmed?'pending':'uncertain',conversation:latest};}
