export const replayCases = [
  {
    "action": "listModels",
    "name": "default",
    "args": {},
    "output": {
      "items": [
        {
          "id": "Kijai/MiniMax-H3-TAE",
          "author": "Kijai",
          "task": null,
          "downloads": 0,
          "likes": 109,
          "parameters": null,
          "gated": false,
          "updatedAt": "2026-08-05T18:40:15.000Z",
          "url": "https://huggingface.co/Kijai/MiniMax-H3-TAE"
        },
        {
          "id": "Akahsizrr/fuse-1-Lite",
          "author": "Akahsizrr",
          "task": "text-generation",
          "downloads": 664,
          "likes": 105,
          "parameters": 5719063552,
          "gated": false,
          "updatedAt": "2026-08-09T12:31:00.000Z",
          "url": "https://huggingface.co/Akahsizrr/fuse-1-Lite"
        },
        {
          "id": "unsloth/MiniMax-H3-GGUF",
          "author": "unsloth",
          "task": "image-text-to-video",
          "downloads": 781,
          "likes": 105,
          "parameters": 20111438744,
          "gated": false,
          "updatedAt": "2026-08-11T01:41:30.000Z",
          "url": "https://huggingface.co/unsloth/MiniMax-H3-GGUF"
        },
        {
          "id": "Wan-AI/Wan2.2-Animate-2-14B",
          "author": "Wan-AI",
          "task": null,
          "downloads": 0,
          "likes": 101,
          "parameters": null,
          "gated": false,
          "updatedAt": "2026-08-09T04:09:19.000Z",
          "url": "https://huggingface.co/Wan-AI/Wan2.2-Animate-2-14B"
        },
        {
          "id": "black-forest-labs/FLUX.1-dev",
          "author": "black-forest-labs",
          "task": "text-to-image",
          "downloads": 475396,
          "likes": 14093,
          "parameters": 11901408320,
          "gated": true,
          "updatedAt": "2025-06-27T16:22:19.000Z",
          "url": "https://huggingface.co/black-forest-labs/FLUX.1-dev"
        },
        {
          "id": "LuffyTheFox/Qwen3.6-35B-A3B-Uncensored-Genesis-Hermes-V7-GGUF",
          "author": "LuffyTheFox",
          "task": "image-text-to-text",
          "downloads": 436140,
          "likes": 472,
          "parameters": 34660610688,
          "gated": false,
          "updatedAt": "2026-08-09T13:33:22.000Z",
          "url": "https://huggingface.co/LuffyTheFox/Qwen3.6-35B-A3B-Uncensored-Genesis-Hermes-V7-GGUF"
        },
        {
          "id": "zai-org/GLM-5.2",
          "author": "zai-org",
          "task": "text-generation",
          "downloads": 2517575,
          "likes": 4929,
          "parameters": 753329940480,
          "gated": false,
          "updatedAt": "2026-07-02T08:08:14.000Z",
          "url": "https://huggingface.co/zai-org/GLM-5.2"
        },
        {
          "id": "SyzygyResearch/Mach-1-Additive-35B",
          "author": "SyzygyResearch",
          "task": null,
          "downloads": 2511,
          "likes": 122,
          "parameters": null,
          "gated": false,
          "updatedAt": "2026-08-11T23:06:51.000Z",
          "url": "https://huggingface.co/SyzygyResearch/Mach-1-Additive-35B"
        },
        {
          "id": "Abiray/Minimax-H3-nvfp4-INT4-INT8-Convrot",
          "author": "Abiray",
          "task": "image-text-to-video",
          "downloads": 565587,
          "likes": 166,
          "parameters": null,
          "gated": false,
          "updatedAt": "2026-08-11T06:42:05.000Z",
          "url": "https://huggingface.co/Abiray/Minimax-H3-nvfp4-INT4-INT8-Convrot"
        },
        {
          "id": "TenStrip/10Eros-Max",
          "author": "TenStrip",
          "task": "image-text-to-video",
          "downloads": 0,
          "likes": 95,
          "parameters": null,
          "gated": false,
          "updatedAt": "2026-08-11T08:29:53.000Z",
          "url": "https://huggingface.co/TenStrip/10Eros-Max"
        },
        {
          "id": "SexGod1979/PinkFluffyBunny-MiniMax-H3",
          "author": "SexGod1979",
          "task": null,
          "downloads": 338,
          "likes": 83,
          "parameters": null,
          "gated": false,
          "updatedAt": "2026-08-09T11:34:56.000Z",
          "url": "https://huggingface.co/SexGod1979/PinkFluffyBunny-MiniMax-H3"
        },
        {
          "id": "Audio8/Audio8-TTS-Preview-0.6b",
          "author": "Audio8",
          "task": "text-to-speech",
          "downloads": 13917,
          "likes": 344,
          "parameters": 601159424,
          "gated": false,
          "updatedAt": "2026-07-31T12:58:38.000Z",
          "url": "https://huggingface.co/Audio8/Audio8-TTS-Preview-0.6b"
        },
        {
          "id": "badtheorylabs/BTL-4",
          "author": "badtheorylabs",
          "task": "text-generation",
          "downloads": 1981,
          "likes": 79,
          "parameters": 35107181936,
          "gated": false,
          "updatedAt": "2026-08-07T06:49:57.000Z",
          "url": "https://huggingface.co/badtheorylabs/BTL-4"
        },
        {
          "id": "NicoLab28/ClipProj-MiniMax-H3",
          "author": "NicoLab28",
          "task": "text-to-video",
          "downloads": 0,
          "likes": 78,
          "parameters": null,
          "gated": false,
          "updatedAt": "2026-08-10T12:50:06.000Z",
          "url": "https://huggingface.co/NicoLab28/ClipProj-MiniMax-H3"
        },
        {
          "id": "realrebelai/MiniMax-H3_GGUFs",
          "author": "realrebelai",
          "task": null,
          "downloads": 195117,
          "likes": 194,
          "parameters": 33122992912,
          "gated": false,
          "updatedAt": "2026-08-08T05:58:24.000Z",
          "url": "https://huggingface.co/realrebelai/MiniMax-H3_GGUFs"
        },
        {
          "id": "Kwaipilot/KAT-Coder-V2.5-Dev",
          "author": "Kwaipilot",
          "task": "text-generation",
          "downloads": 19635,
          "likes": 564,
          "parameters": 34660610688,
          "gated": false,
          "updatedAt": "2026-07-28T04:35:27.000Z",
          "url": "https://huggingface.co/Kwaipilot/KAT-Coder-V2.5-Dev"
        },
        {
          "id": "nvidia/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-BF16",
          "author": "nvidia",
          "task": "text-generation",
          "downloads": 15740,
          "likes": 75,
          "parameters": 31577937344,
          "gated": false,
          "updatedAt": "2026-08-11T23:03:10.000Z",
          "url": "https://huggingface.co/nvidia/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-BF16"
        },
        {
          "id": "HauhauCS/Qwen3.6-35B-A3B-Uncensored-HauhauCS-Aggressive",
          "author": "HauhauCS",
          "task": "image-text-to-text",
          "downloads": 2012637,
          "likes": 3387,
          "parameters": 34660610688,
          "gated": false,
          "updatedAt": "2026-04-17T02:59:21.000Z",
          "url": "https://huggingface.co/HauhauCS/Qwen3.6-35B-A3B-Uncensored-HauhauCS-Aggressive"
        },
        {
          "id": "lodestones/Kroma",
          "author": "lodestones",
          "task": "text-to-image",
          "downloads": 0,
          "likes": 263,
          "parameters": null,
          "gated": false,
          "updatedAt": "2026-08-09T11:42:41.000Z",
          "url": "https://huggingface.co/lodestones/Kroma"
        },
        {
          "id": "Motif-Technologies/Motif-3",
          "author": "Motif-Technologies",
          "task": "text-generation",
          "downloads": 0,
          "likes": 70,
          "parameters": 314841775750,
          "gated": false,
          "updatedAt": "2026-08-11T13:43:45.000Z",
          "url": "https://huggingface.co/Motif-Technologies/Motif-3"
        },
        {
          "id": "DavidAU/Qwen3.5-9B-The-Defiant-Fable-Uncensored-Heretic-NEO-IMATRIX-MAX-MTP-GGUF",
          "author": "DavidAU",
          "task": "image-text-to-text",
          "downloads": 419415,
          "likes": 343,
          "parameters": 8953803264,
          "gated": false,
          "updatedAt": "2026-08-07T02:21:31.000Z",
          "url": "https://huggingface.co/DavidAU/Qwen3.5-9B-The-Defiant-Fable-Uncensored-Heretic-NEO-IMATRIX-MAX-MTP-GGUF"
        },
        {
          "id": "nvidia/NVIDIA-Nemotron-Parse-2.0",
          "author": "nvidia",
          "task": "image-text-to-text",
          "downloads": 4113,
          "likes": 83,
          "parameters": 903049225,
          "gated": false,
          "updatedAt": "2026-08-06T15:16:36.000Z",
          "url": "https://huggingface.co/nvidia/NVIDIA-Nemotron-Parse-2.0"
        },
        {
          "id": "openai/whisper-large-v3",
          "author": "openai",
          "task": "automatic-speech-recognition",
          "downloads": 4813358,
          "likes": 6134,
          "parameters": 1543490560,
          "gated": false,
          "updatedAt": "2024-08-12T10:20:10.000Z",
          "url": "https://huggingface.co/openai/whisper-large-v3"
        },
        {
          "id": "microsoft/Mage-VL",
          "author": "microsoft",
          "task": "image-text-to-text",
          "downloads": 465685,
          "likes": 336,
          "parameters": 4741793792,
          "gated": false,
          "updatedAt": "2026-08-10T09:23:16.000Z",
          "url": "https://huggingface.co/microsoft/Mage-VL"
        },
        {
          "id": "nvidia/Alpamayo2-Super",
          "author": "nvidia",
          "task": "robotics",
          "downloads": 6257,
          "likes": 102,
          "parameters": 35813934322,
          "gated": false,
          "updatedAt": "2026-08-07T05:10:43.000Z",
          "url": "https://huggingface.co/nvidia/Alpamayo2-Super"
        },
        {
          "id": "Qwen/Qwen3.6-27B",
          "author": "Qwen",
          "task": "image-text-to-text",
          "downloads": 6577318,
          "likes": 2229,
          "parameters": 27781427952,
          "gated": false,
          "updatedAt": "2026-04-24T02:39:16.000Z",
          "url": "https://huggingface.co/Qwen/Qwen3.6-27B"
        },
        {
          "id": "deepseek-ai/DeepSeek-V4-Flash",
          "author": "deepseek-ai",
          "task": "text-generation",
          "downloads": 2283943,
          "likes": 2082,
          "parameters": 290944616402,
          "gated": false,
          "updatedAt": "2026-06-22T12:12:13.000Z",
          "url": "https://huggingface.co/deepseek-ai/DeepSeek-V4-Flash"
        },
        {
          "id": "meta-llama/Llama-3.1-8B-Instruct",
          "author": "meta-llama",
          "task": "text-generation",
          "downloads": 7345657,
          "likes": 6582,
          "parameters": 8030261248,
          "gated": true,
          "updatedAt": "2024-09-25T17:00:57.000Z",
          "url": "https://huggingface.co/meta-llama/Llama-3.1-8B-Instruct"
        },
        {
          "id": "thinkingmachines/Inkling-Small",
          "author": "thinkingmachines",
          "task": "image-text-to-text",
          "downloads": 35390,
          "likes": 351,
          "parameters": 265956439090,
          "gated": false,
          "updatedAt": "2026-07-31T00:39:44.000Z",
          "url": "https://huggingface.co/thinkingmachines/Inkling-Small"
        },
        {
          "id": "Cactus-Compute/needle2",
          "author": "Cactus-Compute",
          "task": "text-generation",
          "downloads": 0,
          "likes": 55,
          "parameters": null,
          "gated": false,
          "updatedAt": "2026-08-11T14:42:18.000Z",
          "url": "https://huggingface.co/Cactus-Compute/needle2"
        }
      ],
      "nextCursor": "2"
    }
  },
  {
    "action": "listDatasets",
    "name": "default",
    "args": {},
    "output": {
      "items": [
        {
          "id": "unstonio/pixelgpt-24x24-20k",
          "author": "unstonio",
          "downloads": 7270,
          "likes": 68,
          "gated": false,
          "benchmark": false,
          "updatedAt": "2026-07-30T18:46:34.000Z",
          "url": "https://huggingface.co/datasets/unstonio/pixelgpt-24x24-20k"
        },
        {
          "id": "bench-labs/slop-classification",
          "author": "bench-labs",
          "downloads": 143,
          "likes": 8,
          "gated": false,
          "benchmark": false,
          "updatedAt": "2026-08-11T19:36:23.000Z",
          "url": "https://huggingface.co/datasets/bench-labs/slop-classification"
        },
        {
          "id": "wikimedia/wikipedia",
          "author": "wikimedia",
          "downloads": 228617,
          "likes": 1366,
          "gated": false,
          "benchmark": false,
          "updatedAt": "2024-01-09T09:40:51.000Z",
          "url": "https://huggingface.co/datasets/wikimedia/wikipedia"
        },
        {
          "id": "SWE-bench/SWE-bench_Verified",
          "author": "SWE-bench",
          "downloads": 77234,
          "likes": 137,
          "gated": false,
          "benchmark": true,
          "updatedAt": "2026-08-10T02:06:09.000Z",
          "url": "https://huggingface.co/datasets/SWE-bench/SWE-bench_Verified"
        },
        {
          "id": "IIGroup/X-Coder-SFT-376k",
          "author": "IIGroup",
          "downloads": 1272,
          "likes": 20,
          "gated": false,
          "benchmark": false,
          "updatedAt": "2026-02-07T11:04:07.000Z",
          "url": "https://huggingface.co/datasets/IIGroup/X-Coder-SFT-376k"
        },
        {
          "id": "GokuScraper/seedance-2-prompts-datasets",
          "author": "GokuScraper",
          "downloads": 179705,
          "likes": 25,
          "gated": false,
          "benchmark": false,
          "updatedAt": "2026-08-09T08:12:15.000Z",
          "url": "https://huggingface.co/datasets/GokuScraper/seedance-2-prompts-datasets"
        },
        {
          "id": "AuthenticIlm/Shamela4_Full_DB",
          "author": "AuthenticIlm",
          "downloads": 10006,
          "likes": 18,
          "gated": false,
          "benchmark": false,
          "updatedAt": "2026-05-19T21:04:21.000Z",
          "url": "https://huggingface.co/datasets/AuthenticIlm/Shamela4_Full_DB"
        },
        {
          "id": "databricks/officeqa-pro-v2",
          "author": "databricks",
          "downloads": 207,
          "likes": 7,
          "gated": true,
          "benchmark": false,
          "updatedAt": "2026-08-06T14:42:36.000Z",
          "url": "https://huggingface.co/datasets/databricks/officeqa-pro-v2"
        },
        {
          "id": "moonshotai/PerceptionBench",
          "author": "moonshotai",
          "downloads": 5106,
          "likes": 49,
          "gated": false,
          "benchmark": false,
          "updatedAt": "2026-08-01T09:15:01.000Z",
          "url": "https://huggingface.co/datasets/moonshotai/PerceptionBench"
        },
        {
          "id": "pymaster/CrawlSinger-OS",
          "author": "pymaster",
          "downloads": 106,
          "likes": 8,
          "gated": false,
          "benchmark": false,
          "updatedAt": "2026-08-05T02:58:45.000Z",
          "url": "https://huggingface.co/datasets/pymaster/CrawlSinger-OS"
        },
        {
          "id": "HAERAE-HUB/NOLLI",
          "author": "HAERAE-HUB",
          "downloads": 427,
          "likes": 8,
          "gated": false,
          "benchmark": false,
          "updatedAt": "2026-08-09T08:53:36.000Z",
          "url": "https://huggingface.co/datasets/HAERAE-HUB/NOLLI"
        },
        {
          "id": "nvidia/Nemotron-SFT-Agentic-v2",
          "author": "nvidia",
          "downloads": 6877,
          "likes": 66,
          "gated": false,
          "benchmark": false,
          "updatedAt": "2026-08-10T11:39:11.000Z",
          "url": "https://huggingface.co/datasets/nvidia/Nemotron-SFT-Agentic-v2"
        },
        {
          "id": "nvidia/Nemotron-SFT-Math-v4",
          "author": "nvidia",
          "downloads": 3155,
          "likes": 28,
          "gated": false,
          "benchmark": false,
          "updatedAt": "2026-06-04T04:42:11.000Z",
          "url": "https://huggingface.co/datasets/nvidia/Nemotron-SFT-Math-v4"
        },
        {
          "id": "datacurve/deep-swe",
          "author": "datacurve",
          "downloads": 695,
          "likes": 54,
          "gated": true,
          "benchmark": true,
          "updatedAt": "2026-06-02T19:31:16.000Z",
          "url": "https://huggingface.co/datasets/datacurve/deep-swe"
        },
        {
          "id": "armand0e/claude-fable-5-claude-code",
          "author": "armand0e",
          "downloads": 4597,
          "likes": 350,
          "gated": false,
          "benchmark": false,
          "updatedAt": "2026-06-19T16:23:10.000Z",
          "url": "https://huggingface.co/datasets/armand0e/claude-fable-5-claude-code"
        },
        {
          "id": "markov-ai/gaming-500-hours",
          "author": "markov-ai",
          "downloads": 22497,
          "likes": 246,
          "gated": false,
          "benchmark": false,
          "updatedAt": "2026-06-30T11:56:39.000Z",
          "url": "https://huggingface.co/datasets/markov-ai/gaming-500-hours"
        },
        {
          "id": "allenai/tutormoments-preview",
          "author": "allenai",
          "downloads": 225,
          "likes": 6,
          "gated": false,
          "benchmark": false,
          "updatedAt": "2026-08-06T17:29:07.000Z",
          "url": "https://huggingface.co/datasets/allenai/tutormoments-preview"
        },
        {
          "id": "Jackrong/DeepSeek-V4-Pro-Distilled-200K",
          "author": "Jackrong",
          "downloads": 791,
          "likes": 7,
          "gated": false,
          "benchmark": false,
          "updatedAt": "2026-08-02T14:53:41.000Z",
          "url": "https://huggingface.co/datasets/Jackrong/DeepSeek-V4-Pro-Distilled-200K"
        },
        {
          "id": "ACERobotics/ACE-Data-0",
          "author": "ACERobotics",
          "downloads": 294,
          "likes": 16,
          "gated": false,
          "benchmark": false,
          "updatedAt": "2026-07-31T02:55:59.000Z",
          "url": "https://huggingface.co/datasets/ACERobotics/ACE-Data-0"
        },
        {
          "id": "NCSpeech/YO-CPT-kk",
          "author": "NCSpeech",
          "downloads": 577,
          "likes": 6,
          "gated": false,
          "benchmark": false,
          "updatedAt": "2026-08-04T23:48:02.000Z",
          "url": "https://huggingface.co/datasets/NCSpeech/YO-CPT-kk"
        },
        {
          "id": "ernie-research/FoR-T2I",
          "author": "ernie-research",
          "downloads": 836,
          "likes": 6,
          "gated": false,
          "benchmark": false,
          "updatedAt": "2026-08-05T11:33:06.000Z",
          "url": "https://huggingface.co/datasets/ernie-research/FoR-T2I"
        },
        {
          "id": "OS-Copilot/OSReward",
          "author": "OS-Copilot",
          "downloads": 429,
          "likes": 6,
          "gated": false,
          "benchmark": false,
          "updatedAt": "2026-08-11T17:09:21.000Z",
          "url": "https://huggingface.co/datasets/OS-Copilot/OSReward"
        },
        {
          "id": "ProCreations/approve-or-deny",
          "author": "ProCreations",
          "downloads": 97,
          "likes": 6,
          "gated": false,
          "benchmark": false,
          "updatedAt": "2026-08-09T01:11:29.000Z",
          "url": "https://huggingface.co/datasets/ProCreations/approve-or-deny"
        },
        {
          "id": "histde/ddb-newspaper-corpus",
          "author": "histde",
          "downloads": 47,
          "likes": 6,
          "gated": false,
          "benchmark": false,
          "updatedAt": "2026-08-10T17:42:59.000Z",
          "url": "https://huggingface.co/datasets/histde/ddb-newspaper-corpus"
        },
        {
          "id": "open-thoughts/OpenThoughts-114k",
          "author": "open-thoughts",
          "downloads": 100681,
          "likes": 900,
          "gated": false,
          "benchmark": false,
          "updatedAt": "2025-08-31T00:24:46.000Z",
          "url": "https://huggingface.co/datasets/open-thoughts/OpenThoughts-114k"
        },
        {
          "id": "openbmb/Ultra-FineWeb",
          "author": "openbmb",
          "downloads": 112869,
          "likes": 412,
          "gated": false,
          "benchmark": false,
          "updatedAt": "2026-05-28T04:25:13.000Z",
          "url": "https://huggingface.co/datasets/openbmb/Ultra-FineWeb"
        },
        {
          "id": "mito0o852/OHLCV-1m",
          "author": "mito0o852",
          "downloads": 14268,
          "likes": 55,
          "gated": false,
          "benchmark": false,
          "updatedAt": "2026-05-03T16:22:10.000Z",
          "url": "https://huggingface.co/datasets/mito0o852/OHLCV-1m"
        },
        {
          "id": "HuggingFaceFW/finepdfs",
          "author": "HuggingFaceFW",
          "downloads": 44025,
          "likes": 909,
          "gated": false,
          "benchmark": false,
          "updatedAt": "2026-04-03T19:19:23.000Z",
          "url": "https://huggingface.co/datasets/HuggingFaceFW/finepdfs"
        },
        {
          "id": "ropedia-ai/xperience-10m",
          "author": "ropedia-ai",
          "downloads": 99001,
          "likes": 227,
          "gated": true,
          "benchmark": false,
          "updatedAt": "2026-04-21T05:03:45.000Z",
          "url": "https://huggingface.co/datasets/ropedia-ai/xperience-10m"
        },
        {
          "id": "Glint-Research/Fable-5-traces",
          "author": "Glint-Research",
          "downloads": 50124,
          "likes": 713,
          "gated": false,
          "benchmark": false,
          "updatedAt": "2026-06-29T15:10:20.000Z",
          "url": "https://huggingface.co/datasets/Glint-Research/Fable-5-traces"
        }
      ],
      "nextCursor": "2"
    }
  },
  {
    "action": "listSpaces",
    "name": "video-generation",
    "args": {
      "category": "video-generation"
    },
    "output": {
      "items": [
        {
          "id": "cinderholm/wan2-2-i2v-v3",
          "title": "Wan2.2 14B Fast Preview [NEW]",
          "author": "cinderholm",
          "description": "Generate animated video from a single image with custom prompts",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 867,
          "running": true,
          "updatedAt": "2026-08-07T18:41:13.000Z",
          "url": "https://huggingface.co/spaces/cinderholm/wan2-2-i2v-v3"
        },
        {
          "id": "multimodalart/minimax-h3",
          "title": "MiniMax H3",
          "author": "multimodalart",
          "description": "Generate short videos with synchronized sound from a prompt",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 228,
          "running": true,
          "updatedAt": "2026-08-07T18:58:43.000Z",
          "url": "https://huggingface.co/spaces/multimodalart/minimax-h3"
        },
        {
          "id": "obsxrver/wan22-i2v-omni-lora",
          "title": "Wan2.2 I2V OmniBlink",
          "author": "obsxrver",
          "description": "Generate video from an image with a text prompt",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 220,
          "running": true,
          "updatedAt": "2026-07-27T01:33:23.000Z",
          "url": "https://huggingface.co/spaces/obsxrver/wan22-i2v-omni-lora"
        },
        {
          "id": "wank3r/Wan_2.2_I2V_14B_Custom_Lora_Wow",
          "title": "Wan2.2 14B Custom Lora",
          "author": "wank3r",
          "description": "Create animated videos from a single image",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 83,
          "running": true,
          "updatedAt": "2026-08-02T12:53:48.000Z",
          "url": "https://huggingface.co/spaces/wank3r/Wan_2.2_I2V_14B_Custom_Lora_Wow"
        },
        {
          "id": "mrfakename/minimax-h3-ultra-fast",
          "title": "MiniMax-H3 Ultra Fast",
          "author": "mrfakename",
          "description": "Generate AI videos from text prompts and images",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 76,
          "running": true,
          "updatedAt": "2026-08-08T00:30:21.000Z",
          "url": "https://huggingface.co/spaces/mrfakename/minimax-h3-ultra-fast"
        },
        {
          "id": "kulkas2pintu/wan555",
          "title": "Wan2.2 14B Fast Preview",
          "author": "kulkas2pintu",
          "description": "Generate animated video from a single image and prompt",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 1115,
          "running": true,
          "updatedAt": "2026-07-19T12:27:59.000Z",
          "url": "https://huggingface.co/spaces/kulkas2pintu/wan555"
        },
        {
          "id": "multimodalart/minimax-h3-reference",
          "title": "MiniMax-H3 Reference",
          "author": "multimodalart",
          "description": "Generate video from text and reference media",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 75,
          "running": true,
          "updatedAt": "2026-08-07T18:36:24.000Z",
          "url": "https://huggingface.co/spaces/multimodalart/minimax-h3-reference"
        },
        {
          "id": "akhaliq/MiniMax-H3-Turbo-Lora",
          "title": "MiniMax H3",
          "author": "akhaliq",
          "description": "Generate a video with synced audio from a text prompt",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 43,
          "running": true,
          "updatedAt": "2026-08-11T15:55:34.000Z",
          "url": "https://huggingface.co/spaces/akhaliq/MiniMax-H3-Turbo-Lora"
        },
        {
          "id": "Fighterdan/LTX-2.3-10Eros_I2V",
          "title": "LTX 2.3 10Eros Image-to-Video",
          "author": "Fighterdan",
          "description": "Create videos from images with AI guidance",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 236,
          "running": true,
          "updatedAt": "2026-06-16T16:35:09.000Z",
          "url": "https://huggingface.co/spaces/Fighterdan/LTX-2.3-10Eros_I2V"
        },
        {
          "id": "MiniMaxAI/MiniMax-H3-Turbo-Lora",
          "title": "MiniMax H3",
          "author": "MiniMaxAI",
          "description": "Generate AI video with audio from text and images",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 44,
          "running": true,
          "updatedAt": "2026-08-07T16:07:07.000Z",
          "url": "https://huggingface.co/spaces/MiniMaxAI/MiniMax-H3-Turbo-Lora"
        },
        {
          "id": "bleckhert/uncensored-image-to-video-alchemist",
          "title": "Uncensored Image-to-Video Alchemist 🔥",
          "author": "bleckhert",
          "description": "Generate uncensored videos from your images",
          "category": "Video Generation",
          "sdk": "static",
          "likes": 29,
          "running": true,
          "updatedAt": "2025-12-28T00:58:57.000Z",
          "url": "https://huggingface.co/spaces/bleckhert/uncensored-image-to-video-alchemist"
        },
        {
          "id": "jsoren/wan2-2-fp8da-aoti-preview-2",
          "title": "Wan2.2 14B Fast Preview",
          "author": "jsoren",
          "description": "Generate animated videos from a single image with custom prompts",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 33,
          "running": true,
          "updatedAt": "2026-07-24T01:21:23.000Z",
          "url": "https://huggingface.co/spaces/jsoren/wan2-2-fp8da-aoti-preview-2"
        },
        {
          "id": "Lightricks/LTX-2.5",
          "title": "LTX-2.5",
          "author": "Lightricks",
          "description": "Create video with audio from a text or image prompt",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 13,
          "running": true,
          "updatedAt": "2026-08-11T18:58:33.000Z",
          "url": "https://huggingface.co/spaces/Lightricks/LTX-2.5"
        },
        {
          "id": "hugging-apps/wan2-2-animate-2-14b",
          "title": "Wan2.2 Animate 2 14B",
          "author": "hugging-apps",
          "description": "Animate a character image with motion from a video",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 15,
          "running": true,
          "updatedAt": "2026-08-08T14:56:55.000Z",
          "url": "https://huggingface.co/spaces/hugging-apps/wan2-2-animate-2-14b"
        },
        {
          "id": "Rchoks/wan555",
          "title": "Wan2.2 14B Fast Preview",
          "author": "Rchoks",
          "description": "Generate an animated video from a single image using a prompt",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 67,
          "running": true,
          "updatedAt": "2026-05-17T06:59:50.000Z",
          "url": "https://huggingface.co/spaces/Rchoks/wan555"
        },
        {
          "id": "r3gm/wan2-2-fp8da-aoti-preview",
          "title": "Wan2.2 14B Preview",
          "author": "r3gm",
          "description": "Generate animated video from a single image with custom prompt",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 2972,
          "running": true,
          "updatedAt": "2026-05-15T03:23:22.000Z",
          "url": "https://huggingface.co/spaces/r3gm/wan2-2-fp8da-aoti-preview"
        },
        {
          "id": "Lightricks/LTX-2-3",
          "title": "LTX 2.3 Distilled",
          "author": "Lightricks",
          "description": "Generate cinematic videos with audio from text prompts",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 455,
          "running": true,
          "updatedAt": "2026-05-15T09:36:06.000Z",
          "url": "https://huggingface.co/spaces/Lightricks/LTX-2-3"
        },
        {
          "id": "Parthiban543/wanmanlove",
          "title": "WANMAN",
          "author": "Parthiban543",
          "description": "Generate animated video from an image and prompt",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 12,
          "running": true,
          "updatedAt": "2026-03-26T10:13:36.000Z",
          "url": "https://huggingface.co/spaces/Parthiban543/wanmanlove"
        },
        {
          "id": "zerogpu-aoti/wan2-2-fp8da-aoti-faster",
          "title": "Wan2.2 14B Fast",
          "author": "zerogpu-aoti",
          "description": "Create animated video from a single image",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 3382,
          "running": true,
          "updatedAt": "2026-05-14T17:32:41.000Z",
          "url": "https://huggingface.co/spaces/zerogpu-aoti/wan2-2-fp8da-aoti-faster"
        },
        {
          "id": "kulkas2pintu/wan222",
          "title": "Wan2.2 14B Preview",
          "author": "kulkas2pintu",
          "description": "Generate animated video from a single image with custom prompts",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 215,
          "running": true,
          "updatedAt": "2026-07-19T12:27:46.000Z",
          "url": "https://huggingface.co/spaces/kulkas2pintu/wan222"
        },
        {
          "id": "dream2589632147/Dream-wan2-2-fp8da-aoti-preview-2",
          "title": "Dream Motion Pro - Wan 2.2",
          "author": "dream2589632147",
          "description": "Generate a cinematic video from a single image",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 94,
          "running": true,
          "updatedAt": "2026-07-19T18:34:55.000Z",
          "url": "https://huggingface.co/spaces/dream2589632147/Dream-wan2-2-fp8da-aoti-preview-2"
        },
        {
          "id": "acvlab/abot-world-interactive",
          "title": "ABot-World Interactive",
          "author": "acvlab",
          "description": "Generate a controllable AI‑driven world video from an image prompt",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 93,
          "running": true,
          "updatedAt": "2026-07-12T11:33:52.000Z",
          "url": "https://huggingface.co/spaces/acvlab/abot-world-interactive"
        },
        {
          "id": "signsur4739379373/LTX-2.3-Finetuned-I2V",
          "title": "LTX 2.3 Finetuned I2V",
          "author": "signsur4739379373",
          "description": "Generate custom videos from text prompts and reference images",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 302,
          "running": true,
          "updatedAt": "2026-06-23T21:02:15.000Z",
          "url": "https://huggingface.co/spaces/signsur4739379373/LTX-2.3-Finetuned-I2V"
        },
        {
          "id": "Saravutw/WAN2.2_I2V_LIGHTNING_4-8step_custom",
          "title": "WAN2.2 I2V LIGHTNING-Video-4-8step",
          "author": "Saravutw",
          "description": "Generate animated video from a single image",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 194,
          "running": true,
          "updatedAt": "2026-07-22T19:50:13.000Z",
          "url": "https://huggingface.co/spaces/Saravutw/WAN2.2_I2V_LIGHTNING_4-8step_custom"
        },
        {
          "id": "MarkoVidrih/video-face-swap",
          "title": "Video Face Swap",
          "author": "MarkoVidrih",
          "description": "Swap a face onto a video in seconds",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 69,
          "running": true,
          "updatedAt": "2024-04-01T20:31:40.000Z",
          "url": "https://huggingface.co/spaces/MarkoVidrih/video-face-swap"
        },
        {
          "id": "owenisas/minimax-h3-ref2va",
          "title": "MiniMax-H3 Ref2VA",
          "author": "owenisas",
          "description": "Generate video with synchronized audio from text and reference media",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 6,
          "running": true,
          "updatedAt": "2026-08-11T23:20:38.000Z",
          "url": "https://huggingface.co/spaces/owenisas/minimax-h3-ref2va"
        },
        {
          "id": "hugging-apps/plaguekind-minimax-h3",
          "title": "PlagueKind MiniMax H3",
          "author": "hugging-apps",
          "description": "Generate AI videos with sound from text and optional keyframes",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 6,
          "running": true,
          "updatedAt": "2026-08-04T23:17:23.000Z",
          "url": "https://huggingface.co/spaces/hugging-apps/plaguekind-minimax-h3"
        },
        {
          "id": "tonyassi/video-face-swap",
          "title": "Video Face Swap",
          "author": "tonyassi",
          "description": "Swap a face onto a video and get a preview clip",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 1464,
          "running": true,
          "updatedAt": "2026-05-30T23:54:52.000Z",
          "url": "https://huggingface.co/spaces/tonyassi/video-face-swap"
        },
        {
          "id": "aiguruji97/video-watermark-remover",
          "title": "Video Watermark Remover",
          "author": "aiguruji97",
          "description": "Remove watermarks from videos instantly",
          "category": "Video Generation",
          "sdk": "docker",
          "likes": 97,
          "running": true,
          "updatedAt": "2026-01-15T20:31:19.000Z",
          "url": "https://huggingface.co/spaces/aiguruji97/video-watermark-remover"
        },
        {
          "id": "kulkas2pintu/Video_to_video_WAN",
          "title": "Change Clothes in a Video (by prompt)",
          "author": "kulkas2pintu",
          "description": "Change the outfit in your video using a text prompt",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 10,
          "running": true,
          "updatedAt": "2026-07-30T05:09:14.000Z",
          "url": "https://huggingface.co/spaces/kulkas2pintu/Video_to_video_WAN"
        },
        {
          "id": "meituan-longcat/LongCat-Video-Avatar-1.5-Demo",
          "title": "LongCat-Video-Avatar 1.5",
          "author": "meituan-longcat",
          "description": "Generate a talking video avatar from a photo and audio",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 10,
          "running": true,
          "updatedAt": "2026-06-23T02:42:54.000Z",
          "url": "https://huggingface.co/spaces/meituan-longcat/LongCat-Video-Avatar-1.5-Demo"
        },
        {
          "id": "KlingTeam/LivePortrait",
          "title": "Live Portrait",
          "author": "KlingTeam",
          "description": "Animate a portrait using a driving video",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 3777,
          "running": true,
          "updatedAt": "2024-08-30T11:20:51.000Z",
          "url": "https://huggingface.co/spaces/KlingTeam/LivePortrait"
        },
        {
          "id": "Wan-AI/Wan2.1",
          "title": "Wan2.1",
          "author": "Wan-AI",
          "description": "Generate videos from text or images",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 2152,
          "running": true,
          "updatedAt": "2025-03-20T12:20:36.000Z",
          "url": "https://huggingface.co/spaces/Wan-AI/Wan2.1"
        },
        {
          "id": "Lightricks/ltx-video-distilled",
          "title": "LTX Video Fast",
          "author": "Lightricks",
          "description": "Generate high-quality videos from text, images, or videos",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 1548,
          "running": true,
          "updatedAt": "2026-06-15T08:47:19.000Z",
          "url": "https://huggingface.co/spaces/Lightricks/ltx-video-distilled"
        },
        {
          "id": "asdhms/Omni-Video-Factory-Iframe-API",
          "title": "Omni-Video-Factory-API-iframe",
          "author": "asdhms",
          "description": "Launch the Omni Video Factory interface for video creation",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 12,
          "running": true,
          "updatedAt": "2026-03-13T17:12:16.000Z",
          "url": "https://huggingface.co/spaces/asdhms/Omni-Video-Factory-Iframe-API"
        },
        {
          "id": "thornmaze/wan2-2-i2v-v3",
          "title": "Wan2.2 14B Fast Preview [NEW]",
          "author": "thornmaze",
          "description": "Generate animated video from a single image",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 7,
          "running": true,
          "updatedAt": "2026-08-07T18:41:12.000Z",
          "url": "https://huggingface.co/spaces/thornmaze/wan2-2-i2v-v3"
        },
        {
          "id": "ArianKheir/queenvis-video-segmentation",
          "title": "QueenVIS Video Instance Segmentation",
          "author": "ArianKheir",
          "description": "Segment and track objects in a video clip",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 7,
          "running": true,
          "updatedAt": "2026-07-29T09:09:35.000Z",
          "url": "https://huggingface.co/spaces/ArianKheir/queenvis-video-segmentation"
        },
        {
          "id": "kulkas2pintu/wan666",
          "title": "Wan2.2 14B Fast Preview",
          "author": "kulkas2pintu",
          "description": "Generate animated video from an image",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 6,
          "running": true,
          "updatedAt": "2026-07-19T12:28:06.000Z",
          "url": "https://huggingface.co/spaces/kulkas2pintu/wan666"
        },
        {
          "id": "grow-upcoming/facebook-automation",
          "title": "Facebook Bypass Tool",
          "author": "grow-upcoming",
          "description": "Create edited video clips that bypass copyright detection",
          "category": "Video Generation",
          "sdk": "docker",
          "likes": 4,
          "running": true,
          "updatedAt": "2026-06-23T06:28:06.000Z",
          "url": "https://huggingface.co/spaces/grow-upcoming/facebook-automation"
        },
        {
          "id": "cinderholm/r3gm_wan2-2-fp8da-aoti-preview-2c",
          "title": "Wan2.2 14B Fast Preview",
          "author": "cinderholm",
          "description": "Create animated video from a single image",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 4,
          "running": true,
          "updatedAt": "2026-08-02T16:40:57.000Z",
          "url": "https://huggingface.co/spaces/cinderholm/r3gm_wan2-2-fp8da-aoti-preview-2c"
        },
        {
          "id": "mpasila/minimax-h3-reference-4-step-lora",
          "title": "MiniMax-H3 Reference Custom Lora",
          "author": "mpasila",
          "description": "Generate videos from a prompt and reference media",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 3,
          "running": true,
          "updatedAt": "2026-08-09T17:31:19.000Z",
          "url": "https://huggingface.co/spaces/mpasila/minimax-h3-reference-4-step-lora"
        },
        {
          "id": "mediasynthesismuseum/stable-video-diffusion",
          "title": "Stable Video Diffusion 1.1",
          "author": "mediasynthesismuseum",
          "description": "Generate a short video from a single image",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 2030,
          "running": true,
          "updatedAt": "2026-07-15T13:56:56.000Z",
          "url": "https://huggingface.co/spaces/mediasynthesismuseum/stable-video-diffusion"
        },
        {
          "id": "multimodalart/wan-2-2-first-last-frame",
          "title": "Wan 2 2 First Last Frame",
          "author": "multimodalart",
          "description": "Generate a short video from two images",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 660,
          "running": true,
          "updatedAt": "2026-02-15T16:59:14.000Z",
          "url": "https://huggingface.co/spaces/multimodalart/wan-2-2-first-last-frame"
        },
        {
          "id": "akhaliq/veo3.1-fast",
          "title": "veo3.1-fast",
          "author": "akhaliq",
          "description": "Generate videos from text prompts or images",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 597,
          "running": true,
          "updatedAt": "2025-10-24T08:12:52.000Z",
          "url": "https://huggingface.co/spaces/akhaliq/veo3.1-fast"
        },
        {
          "id": "amirgame197/Remove-Video-Background",
          "title": "Remove Video Background",
          "author": "amirgame197",
          "description": "Remove video backgrounds and export MP4 or WebM",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 363,
          "running": true,
          "updatedAt": "2025-08-29T21:04:45.000Z",
          "url": "https://huggingface.co/spaces/amirgame197/Remove-Video-Background"
        },
        {
          "id": "techfreakworm/LTX2.3-Studio",
          "title": "LTX 2.3 Studio",
          "author": "techfreakworm",
          "description": "Generate videos from text, images, audio, or style",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 317,
          "running": true,
          "updatedAt": "2026-05-19T20:32:55.000Z",
          "url": "https://huggingface.co/spaces/techfreakworm/LTX2.3-Studio"
        },
        {
          "id": "tencent/HY-Motion-1.0",
          "title": "HY-Motion-1.0",
          "author": "tencent",
          "description": "Generate 3D human motion from text prompts",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 298,
          "running": true,
          "updatedAt": "2026-05-22T14:49:47.000Z",
          "url": "https://huggingface.co/spaces/tencent/HY-Motion-1.0"
        },
        {
          "id": "linoyts/LTX-2-3-First-Last-Frame",
          "title": "LTX 2.3 First-Last Frame",
          "author": "linoyts",
          "description": "Generate videos from text, images, and audio",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 153,
          "running": true,
          "updatedAt": "2026-05-14T02:12:33.000Z",
          "url": "https://huggingface.co/spaces/linoyts/LTX-2-3-First-Last-Frame"
        },
        {
          "id": "NihalGazi/FaceFlux-Face-Swapper",
          "title": "FaceFlux - Unlimited Fast Face Swap",
          "author": "NihalGazi",
          "description": "Swap faces in a video using a reference image",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 55,
          "running": true,
          "updatedAt": "2026-06-01T11:04:25.000Z",
          "url": "https://huggingface.co/spaces/NihalGazi/FaceFlux-Face-Swapper"
        },
        {
          "id": "kevinwang676/SadTalker",
          "title": "SadTalker",
          "author": "kevinwang676",
          "description": "Generate a talking face video from an image and audio",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 52,
          "running": true,
          "updatedAt": "2023-07-19T18:24:48.000Z",
          "url": "https://huggingface.co/spaces/kevinwang676/SadTalker"
        },
        {
          "id": "Alissonerdx/ltx-best-face-id",
          "title": "LTX-Best-Face-ID",
          "author": "Alissonerdx",
          "description": "Generate identity-preserving videos from a face photo",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 47,
          "running": true,
          "updatedAt": "2026-07-09T12:47:56.000Z",
          "url": "https://huggingface.co/spaces/Alissonerdx/ltx-best-face-id"
        },
        {
          "id": "STCM/wan2-2-fp8da-aoti-preview-2c-pullout",
          "title": "Wan2.2 14B Pullout + General NSFW lora",
          "author": "STCM",
          "description": "Animate a photo into a short video with custom prompts",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 32,
          "running": true,
          "updatedAt": "2026-07-29T11:39:07.000Z",
          "url": "https://huggingface.co/spaces/STCM/wan2-2-fp8da-aoti-preview-2c-pullout"
        },
        {
          "id": "Lightricks/LTX-2-3-hdr",
          "title": "LTX 2.3 HDR",
          "author": "Lightricks",
          "description": "Generate HDR video from a standard clip using a text prompt",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 27,
          "running": true,
          "updatedAt": "2026-05-09T11:55:34.000Z",
          "url": "https://huggingface.co/spaces/Lightricks/LTX-2-3-hdr"
        },
        {
          "id": "Artex85/LTX2.3-Studio",
          "title": "LTX 2.3 Studio",
          "author": "Artex85",
          "description": "Generate videos from text, images or audio",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 2,
          "running": true,
          "updatedAt": "2026-05-06T16:16:41.000Z",
          "url": "https://huggingface.co/spaces/Artex85/LTX2.3-Studio"
        },
        {
          "id": "MeraTeddBohutBaddaHe/minimax-h3-ultra-fast",
          "title": "MiniMax-H3 Ultra Fast",
          "author": "MeraTeddBohutBaddaHe",
          "description": "Generate short videos with sound from text prompts",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 2,
          "running": true,
          "updatedAt": "2026-08-05T15:16:22.000Z",
          "url": "https://huggingface.co/spaces/MeraTeddBohutBaddaHe/minimax-h3-ultra-fast"
        },
        {
          "id": "hugging-apps/kandinsky-5-time-adapter",
          "title": "Kandinsky 5.0 Time Adapter",
          "author": "hugging-apps",
          "description": "Generate a video from an image with controllable motion speed",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 2,
          "running": true,
          "updatedAt": "2026-08-07T07:51:18.000Z",
          "url": "https://huggingface.co/spaces/hugging-apps/kandinsky-5-time-adapter"
        },
        {
          "id": "hugging-apps/leaptalk-talking-head",
          "title": "LeapTalk",
          "author": "hugging-apps",
          "description": "Generate a talking‑head video from a portrait and speech audio",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 2,
          "running": true,
          "updatedAt": "2026-08-11T14:49:13.000Z",
          "url": "https://huggingface.co/spaces/hugging-apps/leaptalk-talking-head"
        },
        {
          "id": "loveseries/wanmanlove",
          "title": "WANMAN",
          "author": "loveseries",
          "description": "Animate an image into a short video with a prompt",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 197,
          "running": false,
          "updatedAt": "2026-03-26T10:13:36.000Z",
          "url": "https://huggingface.co/spaces/loveseries/wanmanlove"
        },
        {
          "id": "signsur4739379373/Bernini-R-Lightning",
          "title": "Bernini-R Wan 2.2 R2V Lightning",
          "author": "signsur4739379373",
          "description": "Generate videos from reference images and text prompts",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 20,
          "running": false,
          "updatedAt": "2026-06-25T19:44:18.000Z",
          "url": "https://huggingface.co/spaces/signsur4739379373/Bernini-R-Lightning"
        },
        {
          "id": "multimodalart/wan2-1-fast",
          "title": "Wan2.1 Fast",
          "author": "multimodalart",
          "description": "Animate a still image into a short video using a prompt",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 1615,
          "running": true,
          "updatedAt": "2025-07-07T18:38:14.000Z",
          "url": "https://huggingface.co/spaces/multimodalart/wan2-1-fast"
        },
        {
          "id": "fffiloni/LatentSync",
          "title": "LatentSync",
          "author": "fffiloni",
          "description": "Generate lip‑synced video from a video and audio file",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 610,
          "running": true,
          "updatedAt": "2026-05-13T10:58:55.000Z",
          "url": "https://huggingface.co/spaces/fffiloni/LatentSync"
        },
        {
          "id": "alexnasa/ltx-2-TURBO",
          "title": "LTX-2 Video [Turbo]",
          "author": "alexnasa",
          "description": "Generate AI videos from text prompts with optional video cues",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 535,
          "running": true,
          "updatedAt": "2026-07-17T09:20:20.000Z",
          "url": "https://huggingface.co/spaces/alexnasa/ltx-2-TURBO"
        },
        {
          "id": "Wan-AI/Wan2.2-S2V",
          "title": "Wan2.2 S2V",
          "author": "Wan-AI",
          "description": "Generate video from an image and audio file",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 404,
          "running": true,
          "updatedAt": "2025-09-01T07:36:07.000Z",
          "url": "https://huggingface.co/spaces/Wan-AI/Wan2.2-S2V"
        },
        {
          "id": "H-Liu1997/TANGO",
          "title": "TANGO",
          "author": "H-Liu1997",
          "description": "Generate full-body talking video from your audio",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 347,
          "running": true,
          "updatedAt": "2026-05-26T19:26:50.000Z",
          "url": "https://huggingface.co/spaces/H-Liu1997/TANGO"
        },
        {
          "id": "fffiloni/VideoRetalking",
          "title": "VideoRetalking",
          "author": "fffiloni",
          "description": "Generate lip‑synced video from a new audio track",
          "category": "Video Generation",
          "sdk": "docker",
          "likes": 337,
          "running": true,
          "updatedAt": "2025-08-29T11:50:48.000Z",
          "url": "https://huggingface.co/spaces/fffiloni/VideoRetalking"
        },
        {
          "id": "multimodalart/self-forcing",
          "title": "Self Forcing Wan 2.1 ",
          "author": "multimodalart",
          "description": "Generate streaming videos from text prompts in real time",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 327,
          "running": true,
          "updatedAt": "2025-06-26T19:39:05.000Z",
          "url": "https://huggingface.co/spaces/multimodalart/self-forcing"
        },
        {
          "id": "victor/LongCat-Video-Avatar-1.5",
          "title": "LongCat-Video-Avatar 1.5",
          "author": "victor",
          "description": "Generate lip‑synced video from image and audio",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 302,
          "running": true,
          "updatedAt": "2026-05-26T16:44:17.000Z",
          "url": "https://huggingface.co/spaces/victor/LongCat-Video-Avatar-1.5"
        },
        {
          "id": "fffiloni/Meigen-MultiTalk",
          "title": "Meigen MultiTalk",
          "author": "fffiloni",
          "description": "Generate multi-person talking videos from audio and image",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 277,
          "running": true,
          "updatedAt": "2026-05-08T06:48:10.000Z",
          "url": "https://huggingface.co/spaces/fffiloni/Meigen-MultiTalk"
        },
        {
          "id": "Lightricks/ltx-2-distilled",
          "title": "LTX-2 Video Fast",
          "author": "Lightricks",
          "description": "Generate cinematic video with audio from text and image",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 219,
          "running": true,
          "updatedAt": "2026-06-16T15:18:52.000Z",
          "url": "https://huggingface.co/spaces/Lightricks/ltx-2-distilled"
        },
        {
          "id": "ArtificialAnalysis/Video-Generation-Arena-Leaderboard",
          "title": "Video Generation Leaderboard",
          "author": "ArtificialAnalysis",
          "description": "Explore rankings of text‑to‑video generators",
          "category": "Video Generation",
          "sdk": "static",
          "likes": 215,
          "running": true,
          "updatedAt": "2025-06-20T05:07:50.000Z",
          "url": "https://huggingface.co/spaces/ArtificialAnalysis/Video-Generation-Arena-Leaderboard"
        },
        {
          "id": "vinthony/SadTalker",
          "title": "SadTalker",
          "author": "vinthony",
          "description": "Generate a talking face video from an image and audio",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 1428,
          "running": false,
          "updatedAt": "2026-03-25T12:41:12.000Z",
          "url": "https://huggingface.co/spaces/vinthony/SadTalker"
        },
        {
          "id": "zcxu-eric/magicanimate",
          "title": "MagicAnimate",
          "author": "zcxu-eric",
          "description": "Generate animated videos from images and motion sequences",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 1424,
          "running": false,
          "updatedAt": "2023-12-16T06:14:56.000Z",
          "url": "https://huggingface.co/spaces/zcxu-eric/magicanimate"
        },
        {
          "id": "Doubiiu/tooncrafter",
          "title": "ToonCrafter",
          "author": "Doubiiu",
          "description": "Generate animated video from two images and a prompt",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 1056,
          "running": true,
          "updatedAt": "2025-08-28T19:13:03.000Z",
          "url": "https://huggingface.co/spaces/Doubiiu/tooncrafter"
        },
        {
          "id": "zai-org/CogVideoX-5B-Space",
          "title": "CogVideoX-5B",
          "author": "zai-org",
          "description": "Generate short videos from text, images or videos",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 1040,
          "running": true,
          "updatedAt": "2026-05-22T14:01:26.000Z",
          "url": "https://huggingface.co/spaces/zai-org/CogVideoX-5B-Space"
        },
        {
          "id": "fffiloni/zeroscope",
          "title": "Zeroscope Text-To-Video",
          "author": "fffiloni",
          "description": "Generate a video from a text prompt",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 755,
          "running": false,
          "updatedAt": "2024-10-29T14:53:09.000Z",
          "url": "https://huggingface.co/spaces/fffiloni/zeroscope"
        },
        {
          "id": "CVPR/Image-Animation-using-Thin-Plate-Spline-Motion-Model",
          "title": "Image Animation Using Thin Plate Spline Motion Model",
          "author": "CVPR",
          "description": "Generate animated face images using a driving video",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 675,
          "running": true,
          "updatedAt": "2023-10-25T19:06:23.000Z",
          "url": "https://huggingface.co/spaces/CVPR/Image-Animation-using-Thin-Plate-Spline-Motion-Model"
        },
        {
          "id": "Pyramid-Flow/pyramid-flow",
          "title": "Pyramid Flow",
          "author": "Pyramid-Flow",
          "description": "Generate videos from text prompts (optional image guidance)",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 670,
          "running": true,
          "updatedAt": "2024-10-11T14:16:27.000Z",
          "url": "https://huggingface.co/spaces/Pyramid-Flow/pyramid-flow"
        },
        {
          "id": "huggingface-projects/ai-video-composer",
          "title": "AI Video Composer - Natural Language FFMPEG",
          "author": "huggingface-projects",
          "description": "Generate videos from media assets using plain English",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 661,
          "running": true,
          "updatedAt": "2026-01-21T08:02:47.000Z",
          "url": "https://huggingface.co/spaces/huggingface-projects/ai-video-composer"
        },
        {
          "id": "innova-ai/video-background-removal",
          "title": "Video Background Removal",
          "author": "innova-ai",
          "description": "Replace video background with color, image, or video",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 635,
          "running": true,
          "updatedAt": "2025-04-25T04:01:03.000Z",
          "url": "https://huggingface.co/spaces/innova-ai/video-background-removal"
        },
        {
          "id": "KingNish/Instant-Video",
          "title": "Instant Video",
          "author": "KingNish",
          "description": "Generate animated videos from text prompts",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 621,
          "running": false,
          "updatedAt": "2024-08-27T04:59:11.000Z",
          "url": "https://huggingface.co/spaces/KingNish/Instant-Video"
        },
        {
          "id": "fffiloni/Pix2Pix-Video",
          "title": "Pix2Pix Video",
          "author": "fffiloni",
          "description": "Generate edited video frames using text prompts",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 566,
          "running": false,
          "updatedAt": "2025-09-11T14:48:25.000Z",
          "url": "https://huggingface.co/spaces/fffiloni/Pix2Pix-Video"
        },
        {
          "id": "stabilityai/stable-virtual-camera",
          "title": "Stable Virtual Camera",
          "author": "stabilityai",
          "description": "Generate 3D video from input images",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 512,
          "running": false,
          "updatedAt": "2025-08-28T19:18:25.000Z",
          "url": "https://huggingface.co/spaces/stabilityai/stable-virtual-camera"
        },
        {
          "id": "akhaliq/sora-2",
          "title": "Sora 2",
          "author": "akhaliq",
          "description": "Generate videos from text or images",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 485,
          "running": true,
          "updatedAt": "2025-10-25T17:59:43.000Z",
          "url": "https://huggingface.co/spaces/akhaliq/sora-2"
        },
        {
          "id": "ByteDance/AnimateDiff-Lightning",
          "title": "AnimateDiff-Lightning",
          "author": "ByteDance",
          "description": "Create short videos from text prompts",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 406,
          "running": true,
          "updatedAt": "2024-06-07T13:41:10.000Z",
          "url": "https://huggingface.co/spaces/ByteDance/AnimateDiff-Lightning"
        },
        {
          "id": "wangfuyun/AnimateLCM-SVD",
          "title": "AnimateLCM SVD",
          "author": "wangfuyun",
          "description": "Generate animated video from a single image",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 356,
          "running": true,
          "updatedAt": "2026-05-26T19:22:40.000Z",
          "url": "https://huggingface.co/spaces/wangfuyun/AnimateLCM-SVD"
        },
        {
          "id": "akhaliq/Ovi",
          "title": "Ovi",
          "author": "akhaliq",
          "description": "Generate a short video with audio from an image and prompt",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 345,
          "running": true,
          "updatedAt": "2025-10-22T15:55:15.000Z",
          "url": "https://huggingface.co/spaces/akhaliq/Ovi"
        },
        {
          "id": "linoyts/FramePack-F1",
          "title": "FramePack F1",
          "author": "linoyts",
          "description": "Generate short videos from an image and text prompt",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 328,
          "running": true,
          "updatedAt": "2025-09-17T09:30:29.000Z",
          "url": "https://huggingface.co/spaces/linoyts/FramePack-F1"
        },
        {
          "id": "lisonallen/framepack-i2v",
          "title": "FramePack图像到视频生成(5秒限制版)",
          "author": "lisonallen",
          "description": "Generate video from image",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 321,
          "running": false,
          "updatedAt": "2025-04-19T14:53:27.000Z",
          "url": "https://huggingface.co/spaces/lisonallen/framepack-i2v"
        },
        {
          "id": "alexnasa/Wan2.2-Animate-ZEROGPU",
          "title": "Wan2.2 Animate [Local]",
          "author": "alexnasa",
          "description": "Animate video with pose retarget or character swap",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 315,
          "running": true,
          "updatedAt": "2026-05-31T23:59:09.000Z",
          "url": "https://huggingface.co/spaces/alexnasa/Wan2.2-Animate-ZEROGPU"
        },
        {
          "id": "haoheliu/audioldm2-text2audio-text2music",
          "title": "AudioLDM2 Text2Audio Text2Music Generation",
          "author": "haoheliu",
          "description": "Generate audio and waveform video from text",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 307,
          "running": false,
          "updatedAt": "2025-03-24T13:20:52.000Z",
          "url": "https://huggingface.co/spaces/haoheliu/audioldm2-text2audio-text2music"
        },
        {
          "id": "jbilcke-hf/tikslop",
          "title": "TikSlop",
          "author": "jbilcke-hf",
          "description": "Generate videos with TikSlop",
          "category": "Video Generation",
          "sdk": "docker",
          "likes": 306,
          "running": false,
          "updatedAt": "2025-08-06T13:32:29.000Z",
          "url": "https://huggingface.co/spaces/jbilcke-hf/tikslop"
        },
        {
          "id": "zumjoy/Multi-Style_Video-to-Anime_Generator",
          "title": "Multi-Style Video-to-Anime Generator",
          "author": "zumjoy",
          "description": "Transform videos into anime styles",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 287,
          "running": false,
          "updatedAt": "2025-08-03T04:29:43.000Z",
          "url": "https://huggingface.co/spaces/zumjoy/Multi-Style_Video-to-Anime_Generator"
        },
        {
          "id": "facebook/cotracker",
          "title": "CoTracker",
          "author": "facebook",
          "description": "Track points in a video",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 279,
          "running": false,
          "updatedAt": "2024-10-17T18:23:42.000Z",
          "url": "https://huggingface.co/spaces/facebook/cotracker"
        },
        {
          "id": "alexnasa/Ovi-ZEROGPU",
          "title": "Ovi [local]",
          "author": "alexnasa",
          "description": "Generate AI video with audio from a text prompt",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 273,
          "running": true,
          "updatedAt": "2026-05-17T16:14:31.000Z",
          "url": "https://huggingface.co/spaces/alexnasa/Ovi-ZEROGPU"
        },
        {
          "id": "wileewang/TransPixar",
          "title": "TransPixar",
          "author": "wileewang",
          "description": "Generate videos from text prompts",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 249,
          "running": false,
          "updatedAt": "2025-01-08T05:46:59.000Z",
          "url": "https://huggingface.co/spaces/wileewang/TransPixar"
        },
        {
          "id": "cbensimon/wan2-2-fp8da-aoti-preview2",
          "title": "Wan2.2 14B Fast Preview",
          "author": "cbensimon",
          "description": "Generate animated videos from a single image with custom prompts",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 239,
          "running": true,
          "updatedAt": "2026-05-14T11:52:10.000Z",
          "url": "https://huggingface.co/spaces/cbensimon/wan2-2-fp8da-aoti-preview2"
        },
        {
          "id": "depth-anything/Video-Depth-Anything",
          "title": "Video Depth Anything",
          "author": "depth-anything",
          "description": "Generate depth video from input video",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 237,
          "running": true,
          "updatedAt": "2025-03-05T10:44:40.000Z",
          "url": "https://huggingface.co/spaces/depth-anything/Video-Depth-Anything"
        },
        {
          "id": "fffiloni/dreamtalk",
          "title": "Dreamtalk",
          "author": "fffiloni",
          "description": "Create expressive talking head videos from images and audio",
          "category": "Video Generation",
          "sdk": "docker",
          "likes": 229,
          "running": false,
          "updatedAt": "2025-02-26T09:45:29.000Z",
          "url": "https://huggingface.co/spaces/fffiloni/dreamtalk"
        },
        {
          "id": "rahul7star/wan22-AOT",
          "title": "Wan2.2 14B Fast",
          "author": "rahul7star",
          "description": "Create animated videos from a single image and prompt",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 222,
          "running": true,
          "updatedAt": "2026-05-21T01:16:05.000Z",
          "url": "https://huggingface.co/spaces/rahul7star/wan22-AOT"
        },
        {
          "id": "tencent/DepthCrafter",
          "title": "DepthCrafter",
          "author": "tencent",
          "description": "Generate depth maps for your videos",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 208,
          "running": true,
          "updatedAt": "2026-07-14T06:34:39.000Z",
          "url": "https://huggingface.co/spaces/tencent/DepthCrafter"
        },
        {
          "id": "BatuhanYilmaz/Whisper-Auto-Subtitled-Video-Generator",
          "title": "Whisper-Auto-Subtitled-Video-Generator",
          "author": "BatuhanYilmaz",
          "description": "Generate subtitled videos from YouTube links",
          "category": "Video Generation",
          "sdk": "streamlit",
          "likes": 207,
          "running": false,
          "updatedAt": "2024-08-24T15:25:03.000Z",
          "url": "https://huggingface.co/spaces/BatuhanYilmaz/Whisper-Auto-Subtitled-Video-Generator"
        },
        {
          "id": "maxin-cn/Cinemo",
          "title": "Cinemo",
          "author": "maxin-cn",
          "description": "Animate an image into a short video using text prompts",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 204,
          "running": true,
          "updatedAt": "2026-07-14T07:57:27.000Z",
          "url": "https://huggingface.co/spaces/maxin-cn/Cinemo"
        },
        {
          "id": "ZJYang/AniPortrait_official",
          "title": "AniPortrait Official",
          "author": "ZJYang",
          "description": "Create an animated video from audio and a reference image",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 203,
          "running": true,
          "updatedAt": "2026-07-14T11:12:20.000Z",
          "url": "https://huggingface.co/spaces/ZJYang/AniPortrait_official"
        },
        {
          "id": "Skywork/skyreels-a1-talking-head",
          "title": "Skyreels A1 Talking Head",
          "author": "Skywork",
          "description": "Create a talking head video from an image and audio",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 200,
          "running": false,
          "updatedAt": "2025-08-22T04:22:48.000Z",
          "url": "https://huggingface.co/spaces/Skywork/skyreels-a1-talking-head"
        },
        {
          "id": "Vchitect/LaVie",
          "title": "LaVie",
          "author": "Vchitect",
          "description": "Generate videos from text prompts",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 190,
          "running": false,
          "updatedAt": "2025-09-01T09:37:17.000Z",
          "url": "https://huggingface.co/spaces/Vchitect/LaVie"
        },
        {
          "id": "fffiloni/SVFR-demo",
          "title": "SVFR Demo",
          "author": "fffiloni",
          "description": "Restore low-quality face videos with BFR, colorization, inpainting",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 189,
          "running": true,
          "updatedAt": "2026-05-13T10:43:16.000Z",
          "url": "https://huggingface.co/spaces/fffiloni/SVFR-demo"
        },
        {
          "id": "manavisrani07/gradio-lipsync-wav2lip",
          "title": "Gradio Lipsync Wav2lip",
          "author": "manavisrani07",
          "description": "Create lip‑synced videos from a face image and audio",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 185,
          "running": true,
          "updatedAt": "2024-09-07T05:22:32.000Z",
          "url": "https://huggingface.co/spaces/manavisrani07/gradio-lipsync-wav2lip"
        },
        {
          "id": "sczhou/ProPainter",
          "title": "ProPainter",
          "author": "sczhou",
          "description": "Inpaint videos by masking and removing unwanted objects",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 182,
          "running": true,
          "updatedAt": "2026-05-24T19:14:49.000Z",
          "url": "https://huggingface.co/spaces/sczhou/ProPainter"
        },
        {
          "id": "HyperCluster/manimator",
          "title": "Manimator",
          "author": "HyperCluster",
          "description": "Create animations from text or PDFs",
          "category": "Video Generation",
          "sdk": "docker",
          "likes": 178,
          "running": false,
          "updatedAt": "2025-08-16T06:50:34.000Z",
          "url": "https://huggingface.co/spaces/HyperCluster/manimator"
        },
        {
          "id": "hysts/zeroscope-v2",
          "title": "Zeroscope V2",
          "author": "hysts",
          "description": "Generate AI videos from a text prompt",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 177,
          "running": true,
          "updatedAt": "2026-05-27T09:11:54.000Z",
          "url": "https://huggingface.co/spaces/hysts/zeroscope-v2"
        },
        {
          "id": "jiesa/wan2-2-fp8da-aoti-fasterw",
          "title": "Wan2.2 14B Fast",
          "author": "jiesa",
          "description": "Generate a video from an image with a prompt",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 30,
          "running": false,
          "updatedAt": "2025-09-18T09:43:38.000Z",
          "url": "https://huggingface.co/spaces/jiesa/wan2-2-fp8da-aoti-fasterw"
        },
        {
          "id": "wana14/Wan-2.2-5B",
          "title": "Wan 2.2 5B",
          "author": "wana14",
          "description": "Generate high-quality videos from text prompts and images",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 5,
          "running": false,
          "updatedAt": "2025-08-01T23:26:42.000Z",
          "url": "https://huggingface.co/spaces/wana14/Wan-2.2-5B"
        },
        {
          "id": "xyxingx/GR3EN",
          "title": "GR3EN",
          "author": "xyxingx",
          "description": "Relight your video with custom light positions and colors",
          "category": "Video Generation",
          "sdk": "gradio",
          "likes": 3,
          "running": true,
          "updatedAt": "2026-07-27T10:22:01.000Z",
          "url": "https://huggingface.co/spaces/xyxingx/GR3EN"
        }
      ],
      "nextCursor": null
    }
  }
];
