import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { RepositoryPackageSchema, REPOSITORY_VERSIONS } from "../packages/protocol/src/repository.ts";
import { ServiceManifestSchema, APIAuthSchema } from "../packages/protocol/src/manifest.ts";
import { IOSCatalogManifestSchema, MCPCatalogManifestSchema } from "../packages/protocol/src/catalog.ts";
import { ROOT, runCheck } from "./lib.ts";

export function artifacts(): Record<string, string> {
  const schema = {
    $schema: "http://json-schema.org/draft-07/schema#",
    $id: `urn:openox:repository:${REPOSITORY_VERSIONS.at(-1)}`,
    title: "OpenOx Host-Repository content contract",
    $ref: "#/definitions/RepositoryPackage",
    definitions: {
      RepositoryPackage: RepositoryPackageSchema,
      ServiceManifest: ServiceManifestSchema,
      APIAuth: APIAuthSchema,
      IOSCatalogManifest: IOSCatalogManifestSchema,
      MCPCatalogManifest: MCPCatalogManifestSchema,
    },
  };
  const swift = `// Generated by bun tools/repository-contract.ts --write. Do not edit.\n\nnonisolated extension HostProtocols {\n    static let repository = [${REPOSITORY_VERSIONS.join(", ")}]\n}\n`;
  return {
    "packages/protocol/repository.schema.json": JSON.stringify(schema, null, 2) + "\n",
    "apps/ios/Ox/Host/HostRepositoryContract.swift": swift,
  };
}

export async function check(): Promise<string> {
  for (const [path, expected] of Object.entries(artifacts())) {
    const actual = await readFile(join(ROOT, path), "utf8").catch(() => "");
    if (actual !== expected) throw new Error(`${path} is stale; run bun tools/repository-contract.ts --write`);
  }
  return `Host-Repository contract: versions ${REPOSITORY_VERSIONS.join(", ")}, portable schemas and iOS version synchronized`;
}

if (import.meta.main) {
  if (process.argv.includes("--write")) {
    for (const [path, content] of Object.entries(artifacts())) await writeFile(join(ROOT, path), content);
  } else await runCheck(check);
}
