#!/bin/sh
set -eu

: "${OX_DEVELOPMENT_TEAM:?OX_DEVELOPMENT_TEAM is required}"
: "${OX_BUNDLE_IDENTIFIER:?OX_BUNDLE_IDENTIFIER is required}"
: "${OX_APP_GROUP_IDENTIFIER:?OX_APP_GROUP_IDENTIFIER is required}"
: "${OX_ICLOUD_CONTAINER_IDENTIFIER:?OX_ICLOUD_CONTAINER_IDENTIFIER is required}"
: "${OX_KEYCHAIN_SERVICE:?OX_KEYCHAIN_SERVICE is required}"
: "${OX_WEBSITE_DATA_NAMESPACE:?OX_WEBSITE_DATA_NAMESPACE is required}"
: "${OX_AGENT_SKILL_TYPE_IDENTIFIER:?OX_AGENT_SKILL_TYPE_IDENTIFIER is required}"
: "${OX_CHAT_TYPE_IDENTIFIER:?OX_CHAT_TYPE_IDENTIFIER is required}"

umask 077
configuration="$(dirname "$0")/../Local.xcconfig"
printf '%s\n' \
  "OX_DEVELOPMENT_TEAM = $OX_DEVELOPMENT_TEAM" \
  "OX_BUNDLE_IDENTIFIER = $OX_BUNDLE_IDENTIFIER" \
  "OX_APP_GROUP_IDENTIFIER = $OX_APP_GROUP_IDENTIFIER" \
  "OX_ICLOUD_CONTAINER_IDENTIFIER = $OX_ICLOUD_CONTAINER_IDENTIFIER" \
  "OX_KEYCHAIN_SERVICE = $OX_KEYCHAIN_SERVICE" \
  "OX_WEBSITE_DATA_NAMESPACE = $OX_WEBSITE_DATA_NAMESPACE" \
  "OX_AGENT_SKILL_TYPE_IDENTIFIER = $OX_AGENT_SKILL_TYPE_IDENTIFIER" \
  "OX_CHAT_TYPE_IDENTIFIER = $OX_CHAT_TYPE_IDENTIFIER" \
  > "$configuration"
echo "Wrote Xcode Cloud configuration"
